# Streamlit Cloud Secrets Template
# Copy these settings to your Streamlit Cloud app secrets

DEEPSEEK_API_KEY = "your_deepseek_api_key_here"

# Optional: Custom database URL for production
# DB_URL = "sqlite:///production.db"

# Optional: Additional API keys
# OPENAI_API_KEY = "your_openai_key_here"
# ANTHROPIC_API_KEY = "your_anthropic_key_here"

# Get your DeepSeek API key at: https://platform.deepseek.com/api_keys
